source 'https://gitlab.xiaoheiban.cn/iOS/SpecsSwift4.git'
source 'git@github.com/CocoaPods/Specs.git'
#source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'

platform :ios, '9.0'
use_frameworks!
use_modular_headers!
inhibit_all_warnings!

def def_pods
    pod 'UserAuth', :path => '../'
    pod 'Mars', :path => 'submodules/Mars'
end

target 'Example' do
    def_pods
end
