source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
platform :ios, '10.0'

target 'UserAuth_Example' do
  pod 'UserAuth', :path => '../'

  target 'UserAuth_Tests' do
    inherit! :search_paths

    
  end
end
